### PR TITLE
Address TRAC-1041.

### PR DESCRIPTION
**Pull request by markpbaggett**
*JIRA link*: [TRAC-1041](https://jira.lib.utk.edu/browse/TRAC-1041)

# What does this do:

Creates a new xquery script for law and addresses the addition, modification and removal of rules stated in Law Migration XQ script (currently column Q) of this sheet:  https://docs.google.com/spreadsheets/d/1JOXRWpwz0nAnWitHmGyLbfHTTpiBXXXAeqfSeMAJhPo/edit?usp=sharing

# How should you test

Setup BaseX with required plugins and (funct-x), modify the catalog.xq to fit your environment, run to create data uris, and run the base-x-law-to-mods.xq against that.

# Interested Parties

@CanOfBees @cdeaneGit

### CODE REVIEW

**Comment by markpbaggett** [comment]
After talking to @CanOfBees, I realize that I need to assign some variables a little more greedily.  For that reason, please hold off on review until I can do this (a couple of hours.)

**Comment by markpbaggett** [comment]
@CanOfBees since there are no multi-valued fields that would be affected, I think this should be okay. This includes line 49.

Here is a report reflecting this in case there are questions:

| key                                           | types                    | occurrences | percents               |
| --------------------------------------------- | ------------------------ | ----------- | ---------------------- |
| _id                                           | ObjectId                 |        8834 | 100.000000000000000000 |
| metadata                                      | Object                   |        8834 | 100.000000000000000000 |
| metadata.document                             | Object                   |        8834 | 100.000000000000000000 |
| metadata.document.articleid                   | String                   |        8834 | 100.000000000000000000 |
| metadata.document.authors                     | Object (856),null (7978) |        8834 | 100.000000000000000000 |
| metadata.document.context-key                 | String                   |        8834 | 100.000000000000000000 |
| metadata.document.coverpage-url               | String                   |        8834 | 100.000000000000000000 |
| metadata.document.document-type               | String                   |        8834 | 100.000000000000000000 |
| metadata.document.fields                      | Object                   |        8834 | 100.000000000000000000 |
| metadata.document.fields.field                | Array                    |        8834 | 100.000000000000000000 |
| metadata.document.fields.field.XX.@name       | String                   |        8834 | 100.000000000000000000 |
| metadata.document.fields.field.XX.@type       | String                   |        8834 | 100.000000000000000000 |
| metadata.document.fields.field.XX.value       | String                   |        8834 | 100.000000000000000000 |
| metadata.document.label                       | String                   |        8834 | 100.000000000000000000 |
| metadata.document.publication-date            | String                   |        8834 | 100.000000000000000000 |
| metadata.document.publication-title           | String                   |        8834 | 100.000000000000000000 |
| metadata.document.submission-date             | String                   |        8834 | 100.000000000000000000 |
| metadata.document.submission-path             | String                   |        8834 | 100.000000000000000000 |
| metadata.document.title                       | String                   |        8834 | 100.000000000000000000 |
| metadata.document.type                        | String                   |        8834 | 100.000000000000000000 |
| record_id                                     | String                   |        8834 | 100.000000000000000000 |
| series                                        | String                   |        8834 | 100.000000000000000000 |
| metadata.document.fulltext-url                | String                   |        8830 |  99.954720398460494835 |
| metadata.document.disciplines                 | Object                   |        3503 |  39.653611048222778379 |
| metadata.document.disciplines.discipline      | String                   |        3503 |  39.653611048222778379 |
| metadata.document.authors.author              | Object                   |         856 |   9.689834729454380735 |
| metadata.document.authors.author.organization | String                   |         856 |   9.689834729454380735 |
| metadata.document.keywords                    | Object                   |           1 |   0.011319900384876612 |
| metadata.document.keywords.keyword            | String                   |           1 |   0.011319900384876612 |
| metadata.document.native-url                  | String                   |           1 |   0.011319900384876612 |

**Comment by CanOfBees** [comment]
Reviewing this now.

**Review by CanOfBees — APPROVED** [review]
@markpbaggett This looks good; I'm not seeing any ~~glaring~~ issues. Thanks for writing this!

Edit: I'm not seeing *any* issues.

**Pull request merged**
