### PR TITLE
Address Trac-1043.

### PR DESCRIPTION
**Pull request by markpbaggett**
*JIRA link*: [TRAC-1043](https://jira.lib.utk.edu/browse/TRAC-1043)

# What does this do:

Creates a new xquery script for law and addresses the addition, modification and removal of rules stated in the everything else Migration XQ script of this sheet:  https://docs.google.com/spreadsheets/d/1JOXRWpwz0nAnWitHmGyLbfHTTpiBXXXAeqfSeMAJhPo/edit?usp=sharing

# How should you test

Setup BaseX with required plugins and (funct-x), modify the catalog.xq to fit your environment, run to create data uris, and run the base-x-law-to-mods.xq against that.

# Interested Parties

@CanOfBees @cdeaneGit

### CODE REVIEW

**Comment by markpbaggett** [comment]
After talking to @CanOfBees, I realize that I need to assign some variables a little more greedily and implement the same logic that is in TRAC-1019.  For that reason, please hold off on review until I can do this (a couple of hours.)

**Comment by markpbaggett** [comment]
Based on the table below, I need to make sure the rules for these fields are greedy:

1. keywords.keyword
2. disciplines.discipline
3. subject-areas.subject-area

You may be wondering why this isn't a issue with fields.field.XX.value.  That's because the field that is problematic isn't bound or migrated (fields.field[@name="instruct"]/value).

Let me update this and we should be good.

| key                                                       | types                                | occurrences | percents              |
| --------------------------------------------------------- | ------------------------------------ | ----------- | --------------------- |
| _id                                                       | ObjectId                             |       16340 | 100.00000000000000000 |
| metadata                                                  | Object                               |       16340 | 100.00000000000000000 |
| metadata.document                                         | Object                               |       16340 | 100.00000000000000000 |
| metadata.document.articleid                               | String                               |       16340 | 100.00000000000000000 |
| metadata.document.authors                                 | Object (15841),null (499)            |       16340 | 100.00000000000000000 |
| metadata.document.context-key                             | String                               |       16340 | 100.00000000000000000 |
| metadata.document.coverpage-url                           | String                               |       16340 | 100.00000000000000000 |
| metadata.document.document-type                           | String                               |       16340 | 100.00000000000000000 |
| metadata.document.label                                   | String                               |       16340 | 100.00000000000000000 |
| metadata.document.publication-date                        | String                               |       16340 | 100.00000000000000000 |
| metadata.document.publication-title                       | String                               |       16340 | 100.00000000000000000 |
| metadata.document.submission-date                         | String                               |       16340 | 100.00000000000000000 |
| metadata.document.submission-path                         | String                               |       16340 | 100.00000000000000000 |
| metadata.document.title                                   | String                               |       16340 | 100.00000000000000000 |
| metadata.document.type                                    | String                               |       16340 | 100.00000000000000000 |
| record_id                                                 | String                               |       16340 | 100.00000000000000000 |
| series                                                    | String                               |       16340 | 100.00000000000000000 |
| metadata.document.authors.author                          | Object (12700),Array (3136),null (5) |       15841 |  96.94614443084455502 |
| metadata.document.fields                                  | Object                               |       15626 |  95.63035495716034973 |
| metadata.document.fields.field                            | Array (12944),Object (2682)          |       15626 |  95.63035495716034973 |
| metadata.document.fulltext-url                            | String                               |       13293 |  81.35250917992655673 |
| metadata.document.fields.field.XX.@name                   | String                               |       12944 |  79.21664626682986921 |
| metadata.document.fields.field.XX.@type                   | String                               |       12944 |  79.21664626682986921 |
| metadata.document.fields.field.XX.value                   | String (12944),Array (26)            |       12944 |  79.21664626682986921 |
| metadata.document.keywords                                | Object                               |        9118 |  55.80171358629130651 |
| metadata.document.keywords.keyword                        | Array (6904),String (2214)           |        9118 |  55.80171358629130651 |
| metadata.document.disciplines                             | Object                               |        8458 |  51.76254589963280495 |
| metadata.document.disciplines.discipline                  | Array (2878),String (5580)           |        8458 |  51.76254589963280495 |
| metadata.document.authors.author.lname                    | String                               |        7906 |  48.38433292533660079 |
| metadata.document.authors.author.fname                    | String                               |        7473 |  45.73439412484700028 |
| metadata.document.abstract                                | String                               |        6183 |  37.83965728274174012 |
| metadata.document.authors.author.organization             | String                               |        4793 |  29.33292533659730594 |
| metadata.document.authors.author.institution              | String                               |        4270 |  26.13219094247245877 |
| metadata.document.authors.author.mname                    | String                               |        3727 |  22.80905752753977822 |
| metadata.document.authors.author.XX.lname                 | String                               |        3091 |  18.91676866585067174 |
| metadata.document.authors.author.XX.fname                 | String                               |        3089 |  18.90452876376988911 |
| metadata.document.fields.field.@name                      | String                               |        2682 |  16.41370869033047697 |
| metadata.document.fields.field.@type                      | String                               |        2682 |  16.41370869033047697 |
| metadata.document.fields.field.value                      | String                               |        2682 |  16.41370869033047697 |
| metadata.document.authors.author.email                    | String                               |        2324 |  14.22276621787025697 |
| metadata.document.authors.author.XX.mname                 | String                               |        2307 |  14.11872705018359930 |
| metadata.document.authors.author.XX.institution           | String                               |        2013 |  12.31946144430844470 |
| metadata.document.native-url                              | String                               |        1920 |  11.75030599755201877 |
| metadata.document.authors.author.XX.email                 | String                               |         900 |   5.50795593635250924 |
| metadata.document.authors.author.XX.organization          | String                               |         643 |   3.93512851897184834 |
| metadata.document.fpage                                   | String                               |         464 |   2.83965728274173790 |
| metadata.document.subject-areas                           | Object                               |         352 |   2.15422276621787034 |
| metadata.document.subject-areas.subject-area              | String (308),Array (44)              |         352 |   2.15422276621787034 |
| metadata.document.supplemental-files                      | Object                               |         228 |   1.39534883720930236 |
| metadata.document.supplemental-files.file                 | Object (142),Array (86)              |         228 |   1.39534883720930236 |
| metadata.document.authors.author.suffix                   | String                               |         224 |   1.37086903304773555 |
| metadata.document.authors.author.XX.suffix                | String                               |         201 |   1.23011015911872712 |
| metadata.document.lpage                                   | String                               |         192 |   1.17503059975520197 |
| metadata.document.supplemental-files.file.archive-name    | String                               |         142 |   0.86903304773561807 |
| metadata.document.supplemental-files.file.mime-type       | String                               |         142 |   0.86903304773561807 |
| metadata.document.supplemental-files.file.upload-name     | String                               |         142 |   0.86903304773561807 |
| metadata.document.supplemental-files.file.url             | String                               |         142 |   0.86903304773561807 |
| metadata.document.supplemental-files.file.description     | String                               |          96 |   0.58751529987760098 |
| metadata.document.supplemental-files.file.XX.archive-name | String                               |          86 |   0.52631578947368418 |
| metadata.document.supplemental-files.file.XX.mime-type    | String                               |          86 |   0.52631578947368418 |
| metadata.document.supplemental-files.file.XX.upload-name  | String                               |          86 |   0.52631578947368418 |
| metadata.document.supplemental-files.file.XX.url          | String                               |          86 |   0.52631578947368418 |
| metadata.document.supplemental-files.file.XX.description  | String                               |          66 |   0.40391676866585069 |
| metadata.document.fields.field.XX.@list                   | String                               |          34 |   0.20807833537331702 |
| metadata.document.withdrawn                               | String                               |          10 |   0.06119951040391677 |

**Comment by markpbaggett** [comment]
Alright.  Added the new embargo logic.  Should be safe to review.

**Comment by CanOfBees** [comment]
Reviewing this now.

**Comment by CanOfBees** [comment]
@markpbaggett I'd like to throw a little more test data through the conversion before I approve and there's one syntax error: see [line 54](https://github.com/markpbaggett/basex-bepress-to-mods/blob/TRAC-1043/bepress-everything-else-to-mods.xq#L54):

`.../subject-areas///subject-area/...` should be `.../subject-areas//subject-area/...`

**Comment by markpbaggett** [comment]
@CanOfBees extra greedy slash was removed.

**Review by CanOfBees — COMMENTED** [review]
One question and this can be approved: do we only want to add the `mods:affiliation` elements when `$dept-name`, `$college`, or `$institution` are available?

I'm asking in the context of using a Form to update a migrated MODS dsid -- won't read operations break if the `mods:affiliation`s are missing?

Otherwise this works on all of my tests.

**Comment by markpbaggett** [comment]
@CanOfBees not sure I understand.

The form will read an affiliation if ti's available.  It would also add one if it didn't exist or replace if it did.

We don't want to add bad data.  We can't assume any of this for this particular metadata mapping.  I see no reason to add blank nodes for the sake of blank nodes.

**Comment by CanOfBees** [comment]
@markpbaggett sounds good to me.

**Comment by CanOfBees** [comment]
Approved and merged.

**Pull request merged**
